services:
  - type: web
    name: roodle
    runtime: go
    branch: main
    buildCommand: bash build.sh
    startCommand: ./bin/app
    rootDir: .
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: OAUTH2_GOOGLE_CREDENTIALS_FILE
        value: /etc/secrets/clientid.google.json
      - key: DATABASE_URL
        sync: false
      - key: COOKIE_SECRET
        sync: false
